### ISSUE TITLE
[ERROR] [main.py:197] Unexpected error 'cp949' codec can't decode byte 0xe5 in position 18: illegal multibyte sequence

### ISSUE THREAD

**Issue by lisegok1** [Galactic647/GI-3DMigoto-Tools#1] opened 2023-04-13 22:26 UTC
troubleshooting with this error

**Comment by Galactic647** [comment] 2023-04-15 15:27
This is caused by unhandled encoding error when reading a file, but this error has been fixed now with the latest release

**Closed as completed** 2023-04-15 15:43 UTC
Labels: bug
